#!/bin/bash
# Reject if API key is in info.plist

set -e

exec 1>&2 # Redirect output to stderr.

root="$( git rev-parse --show-toplevel )"
ip="$root/src/info.plist"

test -f "$ip" || { echo "$ip not found"; exit 1; }
value="$( /usr/libexec/PlistBuddy -c 'Print :variables:GOOGLE_PLACES_API_KEY' "$ip" )"
test -n "$value" && { echo "GOOGLE_PLACES_API_KEY is set info.plist"; exit 1; }

exit 0
