#!/usr/bin/env python
# encoding: utf-8
#
# Copyright (c) 2016 Dean Jackson <deanishe@deanishe.net>
#
# MIT Licence. See http://opensource.org/licenses/MIT
#
# Created on 2016-03-13
#

"""
"""

from __future__ import print_function, unicode_literals, absolute_import

import os
import sys

path = os.path.abspath(os.path.join(os.path.dirname(__file__), 'lib'))
if path not in sys.path:
    sys.path.insert(0, path)


if __name__ == '__main__':
    from searchio.cli import main
    main()
